import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    title: "Disaster Response Portal",
    subtitle: "Real-time coordination and reporting platform",
    emergencyReport: "Report Emergency",
    myReports: "My Reports",
    alerts: "Alerts & Advisories",
    login: "Login",
    register: "Register",
    logout: "Logout",
    citizenPortal: "Citizen Portal",
    dashboard: "Authority Dashboard",
    analytics: "Response Analytics",
    disasterType: "Disaster Type",
    severity: "Severity Level",
    affectedPeople: "Affected People",
    description: "Short Description",
    locality: "Locality / Landmark",
    locationCapture: "Capture Geolocation",
    locationCaptured: "Location Captured Successfully",
    locationDenied: "Location permission denied. Click map to set pin.",
    photoUpload: "Upload Photograph",
    submit: "Submit Emergency Report",
    submitting: "Submitting report...",
    status: "Status",
    reported: "Reported",
    verified: "Verified",
    awaitingAllocation: "Awaiting Allocation",
    resourceAssigned: "Rescue Team Assigned",
    rescueInProgress: "Rescue In Progress",
    resolved: "Resolved",
    duplicate: "Potential Duplicate",
    rejected: "Rejected",
    selectLocationOnMap: "Double-click map to specify location",
    nearestTeam: "Recommended Rescue Team",
    assignTeam: "Assign Team",
    viewAlternatives: "View Alternatives",
    noTeamAvailable: "No suitable team available within 20 km",
    critical: "Critical",
    high: "High",
    medium: "Medium",
    low: "Low",
    distance: "Distance",
    reason: "Reason",
    activeIncidents: "Active Incidents",
    rescueTeams: "Rescue Teams",
    shelters: "Shelters",
    supplies: "Supply Depots",
    waterStock: "Water Stock",
    foodStock: "Food Stock",
    medicalStock: "Medical Stock",
    capacity: "Capacity",
    occupied: "Occupied",
    available: "Available",
    enRoute: "En Route",
    rescuing: "Rescuing",
    assigned: "Assigned",
    open: "Open",
    full: "Full",
    nearCapacity: "Near Capacity",
    searchPlaceholder: "Search incidents...",
    filterSeverity: "Filter Severity",
    filterType: "Filter Type",
    all: "All",
    language: "Language",
    smsSim: "SMS Simulator",
    ivrSim: "IVR Hotline Simulator",
    triggerAlert: "IMD Weather Warning Feed",
    recommendShelter: "Allocate Shelter",
    recommendSupplies: "Distribute Relief Supplies",
    allocate: "Allocate Space",
    distribute: "Distribute Stock"
  },
  hi: {
    title: "आपदा प्रतिक्रिया पोर्टल",
    subtitle: "वास्तविक समय समन्वय और रिपोर्टिंग मंच",
    emergencyReport: "आपातकाल की रिपोर्ट करें",
    myReports: "मेरी रिपोर्टें",
    alerts: "अलर्ट और चेतावनी",
    login: "लॉगिन",
    register: "पंजीकरण",
    logout: "लॉगआउट",
    citizenPortal: "नागरिक पोर्टल",
    dashboard: "अधिकारी डैशबोर्ड",
    analytics: "प्रतिक्रिया विश्लेषण",
    disasterType: "आपदा का प्रकार",
    severity: "गंभीरता का स्तर",
    affectedPeople: "प्रभावित लोग",
    description: "संक्षिप्त विवरण",
    locality: "इलाका / सीमा चिन्ह",
    locationCapture: "भू-स्थान कैप्चर करें",
    locationCaptured: "स्थान सफलतापूर्वक कैप्चर किया गया",
    locationDenied: "स्थान की अनुमति अस्वीकृत। पिन सेट करने के लिए मानचित्र पर क्लिक करें।",
    photoUpload: "फोटो अपलोड करें",
    submit: "आपातकालीन रिपोर्ट जमा करें",
    submitting: "रिपोर्ट जमा की जा रही है...",
    status: "स्थिति",
    reported: "रिपोर्ट दर्ज",
    verified: "सत्यापित",
    awaitingAllocation: "आवंटन की प्रतीक्षा है",
    resourceAssigned: "बचाव दल आवंटित",
    rescueInProgress: "बचाव कार्य जारी",
    resolved: "सुलझाया गया",
    duplicate: "संभावित प्रतिलिपि",
    rejected: "अस्वीकृत",
    selectLocationOnMap: "स्थान निर्दिष्ट करने के लिए मानचित्र पर डबल-क्लिक करें",
    nearestTeam: "अनुशंसित बचाव दल",
    assignTeam: "दल नियुक्त करें",
    viewAlternatives: "विकल्प देखें",
    noTeamAvailable: "20 किमी के भीतर कोई उपयुक्त टीम उपलब्ध नहीं है",
    critical: "अत्यंत गंभीर",
    high: "गंभीर",
    medium: "मध्यम",
    low: "निम्न",
    distance: "दूरी",
    reason: "कारण",
    activeIncidents: "सक्रिय घटनाएं",
    rescueTeams: "बचाव दल",
    shelters: "राहत शिविर",
    supplies: "आपूर्ति डिपो",
    waterStock: "पानी का स्टॉक",
    foodStock: "खाद्य सामग्री स्टॉक",
    medicalStock: "चिकित्सा स्टॉक",
    capacity: "क्षमता",
    occupied: "भरी हुई",
    available: "उपलब्ध",
    enRoute: "रास्ते में",
    rescuing: "बचाव जारी",
    assigned: "आवंटित",
    open: "खुला है",
    full: "पूरा भरा",
    nearCapacity: "क्षमता के करीब",
    searchPlaceholder: "घटनाओं को खोजें...",
    filterSeverity: "गंभीरता फ़िल्टर",
    filterType: "प्रकार फ़िल्टर",
    all: "सभी",
    language: "भाषा",
    smsSim: "एसएमएस सिम्युलेटर",
    ivrSim: "आईवीआर हॉटलाइन सिम्युलेटर",
    triggerAlert: "आईएमडी मौसम चेतावनी",
    recommendShelter: "शिविर आवंटित करें",
    recommendSupplies: "राहत सामग्री वितरित करें",
    allocate: "स्थान आवंटित करें",
    distribute: "सामग्री वितरित करें"
  },
  or: {
    title: "ବିପର୍ଯ୍ୟୟ ପ୍ରଶମନ ପୋର୍ଟାଲ",
    subtitle: "ରିଅଲ-ଟାଇମ୍ ସମନ୍ୱୟ ଏବଂ ରିପୋର୍ଟିଂ ପ୍ଲାଟଫର୍ମ",
    emergencyReport: "ଜରୁରୀକାଳୀନ ରିପୋର୍ଟ କରନ୍ତୁ",
    myReports: "ମୋର ରିପୋର୍ଟ",
    alerts: "ବିପର୍ଯ୍ୟୟ ସୂଚନା ଓ ସତର୍କତା",
    login: "ଲଗଇନ୍",
    register: "ପଞ୍ଜୀକରଣ",
    logout: "ଲଗଆଉଟ୍",
    citizenPortal: "ନାଗରିକ ପୋର୍ଟାଲ",
    dashboard: "କର୍ତ୍ତୃପକ୍ଷ ଡ୍ୟାସବୋର୍ଡ",
    analytics: "ପ୍ରତିକ୍ରିୟା ବିଶ୍ଳେଷଣ",
    disasterType: "ବିପର୍ଯ୍ୟୟ ପ୍ରକାର",
    severity: "ଗମ୍ଭୀରତା ସ୍ତର",
    affectedPeople: "ପ୍ରଭାବିତ ଲୋକ ସଂଖ୍ୟା",
    description: "ସଂକ୍ଷିପ୍ତ ବିବରଣୀ",
    locality: "ସ୍ଥାନୀୟ ଅଞ୍ଚଳ / ଲ୍ୟାଣ୍ଡମାର୍କ",
    locationCapture: "ଜିପିଏସ୍ ଅବସ୍ଥିତି ଚିହ୍ନଟ",
    locationCaptured: "ଅବସ୍ଥିତି ସଫଳତାର ସହ ଚିହ୍ନଟ ହେଲା",
    locationDenied: "ଜିପିଏସ୍ ଅନୁମତି ମିଳିଲାନି। ମ୍ୟାପ୍ ଉପରେ କ୍ଲିକ୍ କରି ପିନ୍ ସେଟ୍ କରନ୍ତୁ।",
    photoUpload: "ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ",
    submit: "ଜରୁରୀକାଳୀନ ରିପୋର୍ଟ ଦାଖଲ",
    submitting: "ରିପୋର୍ଟ ଦାଖଲ ହେଉଛି...",
    status: "ସ୍ଥିତି",
    reported: "ରିପୋର୍ଟ ଦାଖଲ",
    verified: "ଯାଞ୍ଚ ହୋଇଛି",
    awaitingAllocation: "ବଣ୍ଟନ ଅପେକ୍ଷାରେ",
    resourceAssigned: "ଉଦ୍ଧାରକାରୀ ଦଳ ନିୟୋଜିତ",
    rescueInProgress: "ଉଦ୍ଧାର କାର୍ଯ୍ୟ ଜାରି",
    resolved: "ସମାଧାନ ହୋଇଛି",
    duplicate: "ସମ୍ଭାବ୍ୟ ନକଲି ରିପୋର୍ଟ",
    rejected: "ପ୍ରତ୍ୟାଖ୍ୟାତ",
    selectLocationOnMap: "ନିର୍ଦ୍ଦିଷ୍ଟ ସ୍ଥାନ ଚିହ୍ନଟ କରିବା ପାଇଁ ମ୍ୟାପ୍ ଉପରେ ଡବଲ୍-କ୍ଲିକ୍ କରନ୍ତୁ",
    nearestTeam: "ସୁପାରିଶକୃତ ଉଦ୍ଧାରକାରୀ ଦଳ",
    assignTeam: "ଦଳ ନିଯୁକ୍ତ କରନ୍ତु",
    viewAlternatives: "ଅନ୍ୟ ବିକଳ୍ପ ଦେଖନ୍ତୁ",
    noTeamAvailable: "୨୦ କିମି ମଧ୍ୟରେ କୌଣସି ଉପଯୁକ୍ତ ଦଳ ଉପଲବ୍ଧ ନାହିଁ",
    critical: "ଅତ୍ୟନ୍ତ ଜରୁରୀ",
    high: "ଗୁରୁତର",
    medium: "ମଧ୍ୟମ",
    low: "ସାଧାରଣ",
    distance: "ଦୂରତା",
    reason: "କାରଣ",
    activeIncidents: "ସକ୍ରିୟ ବିପର୍ଯ୍ୟୟ",
    rescueTeams: "ଉଦ୍ଧାରକାରୀ ଦଳ",
    shelters: "ବାତ୍ୟା ଆଶ୍ରୟସ୍ଥଳୀ",
    supplies: "ଆପତ୍ତକାଳୀନ ଆପୂର୍ତ୍ତି କେନ୍ଦ୍ର",
    waterStock: "ପାନୀୟ ଜଳ ମହଜୁଦ",
    foodStock: "ଖାଦ୍ୟ ସାମଗ୍ରୀ ମହଜୁଦ",
    medicalStock: "ଔଷଧ ପତ୍ର ମହଜୁଦ",
    capacity: "କ୍ଷମତା",
    occupied: "ବ୍ୟବହୃତ",
    available: "ଉପଲବ୍ଧ",
    enRoute: "ଯାତ୍ରା କରୁଛନ୍ତି",
    rescuing: "ଉଦ୍ଧାର କରୁଛନ୍ତି",
    assigned: "ନିୟୋଜିତ",
    open: "ଖୋଲା ଅଛି",
    full: "ସମ୍ପୂର୍ଣ୍ଣ ବ୍ୟବହୃତ",
    nearCapacity: "କ୍ଷମତା ଶେଷ ହେବାକୁ ଯାଉଛି",
    searchPlaceholder: "ଘଟଣା ଖୋଜନ୍ତୁ...",
    filterSeverity: "ଗମ୍ଭୀରତା ଫିଲ୍ଟର୍",
    filterType: "ପ୍ରକାର ଫିଲ୍ଟର୍",
    all: "ସମସ୍ତ",
    language: "ଭାଷା",
    smsSim: "ଏସଏମଏସ ସିମୁଲେଟର",
    ivrSim: "ଆଇଭିଆର ହଟଲାଇନ ସିମୁଲେଟର",
    triggerAlert: "ଆଇଏମଡି ପାଣିପାଗ ସତର୍କ ସୂଚନା",
    recommendShelter: "ଆଶ୍ରୟସ୍ଥଳୀ ଆବଣ୍ଟନ",
    recommendSupplies: "ରିଲିଫ୍ ସାମଗ୍ରୀ ବଣ୍ଟନ",
    allocate: "ସ୍ଥାନ ଆବଣ୍ଟନ",
    distribute: "ସାମଗ୍ରୀ ବଣ୍ଟନ"
  }
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const lang = 'en';
  const setLang = () => {};

  const t = (key) => {
    return translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

